version: '3'

services:
   api:
      build:
         context: ./api
      environment:
         PGUSER: postgres
         PGPASSWORD: postgres
         PGDATABASE: timemanager_dev
         PGPORT: 5432
         PGHOST: db
      ports:
         - 4000:4000
      depends_on:
         - db
   db:
      image: postgres:latest
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         PGDATA: /var/lib/postgresql/data/pgdata
      restart: always
      volumes:
         - pgdata:/var/lib/postgresql/data
   client:
      build:
         context: ./client
      ports:
         - 8080:8080
volumes:
   pgdata: